### PR TITLE
Add cluster tags in the bucket too

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/aws-operator/issues/662

Add cluster tags to the S3 buckets too

### CODE REVIEW

**Comment by pipo02mix** [comment]
I have tested on gauss with a new cluster but I can not see any tag added in the bucket of the guest cluster. I will add more logging to check was going on

**Comment by rossf7** [comment]
@pipo02mix Tested your branch and its working fine for me.

```
aws s3api get-bucket-tagging --bucket 084190472784-g8s-ross-cluster --region eu-central-1 
{
    "TagSet": [
        {
            "Value": "owned",
            "Key": "kubernetes.io/cluster/ross-cluster"
        }
    ]
}
```

**Comment by pipo02mix** [comment]
hehe Then it is my fault I could not see in aws console the tags. Great, I merge it then

**Comment by rossf7** [comment]
Yes, I find the new S3 section of the AWS console confusing. I liked the old design more! ;)

**Pull request merged**
