### PR TITLE
Revert "refactored output adapter"

### PR DESCRIPTION
**Pull request by xh3b4sd**
Reverts giantswarm/aws-operator#752

### CODE REVIEW

**Comment by xh3b4sd** [comment]
@fgimenez @rossf7 @kopiczko FYI I got a very uncomfortable feeling with this. I realized the change means that guest clusters get updated, which they should not. I added the version bundle version to the stack state and we compare current and desired state but even after the update the clusters do not have the version bundle version AFAIK. I need to test a bit more with this. Right now I fear the clusters would get updated over and over again without anything really changing. This implies disturbing customer workloads for no real reason. I am also wondering how to roll this out then. Do I miss something? Am I wrong with this? Are we safe?

**Comment by fgimenez** [comment]
If the version bundle version doesn't change there's no update triggered. Currently we are reconciliating comparing values obtained from the custom object (desired state https://github.com/giantswarm/aws-operator/blob/master/service/awsconfig/v5/resource/cloudformation/main_stack.go#L15) and values from the stack outputs (current state https://github.com/giantswarm/aws-operator/blob/master/service/awsconfig/v5/resource/cloudformation/current.go#L59-L97). If there's no change we don't update see https://github.com/giantswarm/aws-operator/blob/master/service/awsconfig/v5/resource/cloudformation/update.go#L71. In the e2e tests we change the number of workers in the custom object and only then the operator triggers an update. Being an additional field in the state version bundle versions should work the same way.

Also, this change only affects the WIP version, there are clusters without exposing the version bundle version in the outputs but the operator won't try to check the value for them, pls correct me if I'm wrong.

**Comment by xh3b4sd** [comment]
> Also, this change only affects the WIP version, there are clusters without exposing the version bundle version in the outputs but the operator won't try to check the value for them, pls correct me if I'm wrong.

Oh yeah man. Totally. For a moment I thought the old clusters will be updated as well but you are right. This here is just the WIP version. So as soon as people start clusters which the v5 resources reconcile the update magic applies, but not for older clusters. 

This brings a question up though. How do we actually update the outputs for a cloudformation stack? At some point we want to update guest clusters because their version bundle version changed, but then what I feared here happens. We upgrade and change the stack outputs but they will never change because I remember you saying that we can only set the stack outputs once and then they cannot be changed anymore. In order to make updates work we would need to change the stack outputs though, to change the version bundle version we updated to.

**Comment by fgimenez** [comment]
> We upgrade and change the stack outputs but they will never change because I remember you saying that we can only set the stack outputs once and then they cannot be changed anymore

Nope, when we know that we should do an update we recreate the whole stack template based on the current custom object (this is how stacks are updated, you resend the whole template and CF is clever enough to only modify the resources that need to be changed), see https://github.com/giantswarm/aws-operator/blob/master/service/awsconfig/v5/resource/cloudformation/update.go#L74, so that the new version bundle version will be put in the right place in the outputs and the state is always in sync.

**Comment by xh3b4sd** [comment]
Ok cool. Then I misunderstood the current implementation. I was under the impression we update the stack, instead of re-creating it, because we call `r.clients.CloudFormation.UpdateStack`. Did not know about the internals. 

I will then revert the revert. Thanks for talking this through. Better safe than sorry. :D

**Comment by fgimenez** [comment]
> I was under the impression we update the stack, instead of re-creating it, because we call r.clients.CloudFormation.UpdateStack

Sure, in terms of the API call we are doing an update, I meant that we recreate the stack template (the `TemplateBody` of the `UpdateStackInput` object https://github.com/giantswarm/aws-operator/blob/master/service/awsconfig/v5/resource/cloudformation/update.go#L79), and send that in the update call.

**Pull request merged**
