### PR TITLE
[WIP] CloudFormation for the workers ASG

### LINKED ISSUE #322: CloudFormation for Workers
We decided to try out CloudFormation on the workers ASG. The initial implementation will deal with scaling the workers up/down.

Benefits:

* Declarative
* Easier to do rolling updates when the CC changes
* Allows us to simplify the operator

Cons:

* Rolling updates are only triggered on LC change. How do we tie the 2 CCs together, so that the LC changes when the big CC changes?
* Passing in variable-sized parameters (e.g. ELB listeners) is [very cumbersome](https://stackoverflow.com/a/44289165/112538). We might want to use a Go template with proper for loops, instead of relying on AWS' broken system.

Limits:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

### PR DESCRIPTION
**Pull request by asymmetric**
# WIP

Use CloudFormation for the workers ASG.

* Calculate checksum of big CC
* Use it in the small CC
* This way, when the big CC changes, the small one does too
* Ergo, the LC changes
* Ergo, the ASG can get a rolling update

Closes #322.

### CODE REVIEW

**Comment by asymmetric** [comment]
### Status Update

We create a template that contains the LC and the ASG. Other inputs (the LB, the SG rules etc) are still created via the API, as I haven't found an easy way to pass in arguments with variable length (e.g., the SG rules).

**Comment by xh3b4sd** [comment]
What about this PR? Is it still relevant? Should we close it?

**Comment by asymmetric** [comment]
This is what I was working on the last weeks before leaving, I think @rossf7 wanted to take a look and evaluate whether it makes sense to proceed.

**Comment by rossf7** [comment]
Thanks @asymmetric  Yes I'll need this PR when I pick up Cloud Formation. I've assigned myself.

**Pull request closed without merging**
