### PR TITLE
wire v18patch1

### PR DESCRIPTION
**Pull request by teemow**

### CODE REVIEW

**Comment by teemow** [comment]
@xh3b4sd you mentioned here: https://github.com/giantswarm/aws-operator/pull/1251#pullrequestreview-172964364 that the drainer wiring is missing. what needs to be done for that?

**Comment by xh3b4sd** [comment]
Same as with `service/controller/cluster.go` but with `service/controller/drainer.go`.

**Comment by teemow** [comment]
Thanks. Done.

**Comment by teemow** [comment]
changelog is already here: https://github.com/giantswarm/aws-operator/pull/1247

**Pull request merged**
