### PR TITLE
controller/v14patch1: update imports and packages

### PR DESCRIPTION
**Pull request by rossf7**

### CODE REVIEW

**Comment by rossf7** [comment]
@xh3b4sd Its for the Ingress Controller migration. Changes are added to the 5.0.0 release for K8s 1.11 but it will take time for customers to move.

So the patch release is for upgrading K8s 1.10 clusters.

**Comment by xh3b4sd** [comment]
I see. Anything we can take away from this? Anything we can do better with planning or something we can tweak in our strategies? To me it feels like as soon as we have to patch something in older versions we did something wrong in the first place.

**Comment by puja108** [comment]
I do not think we did something wrong here, it's mainly a fact of our customer environment that most customers will not directly go for 1.11 and as we have seen in the past IC is a very central component, which often needs updating/patching, so we decided that we want to bring the "managed IC" to both the 1.10 and the 1.11 branch. This is just a thing that we will need to live with as long as we are supporting 2 current major versions (i.e. 2 minor k8s versions) at a time. This can be understood as cherry-picking things that will help us in support shifts back to the older supported version.

**Comment by rossf7** [comment]
Yes I think its also why we need release-operator and the git based approach for versioning our operators. That should make this type of cherry picking a lot easier.

**Pull request merged**
