### PR TITLE
HA Masters

### PR DESCRIPTION
**Pull request by xh3b4sd**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

## Context 

We use this branch to merge all HA Masters related feature branches together.

### CODE REVIEW

**Comment by calvix** [comment]
`hama` reporting for duty :trollface:

**Comment by calvix** [comment]
OK let's test this and see if we make seamlessly merge to master without causing troubles

**Comment by xh3b4sd** [comment]
Who is we now? I am busy with https://github.com/giantswarm/aws-operator/pull/2474 right now.

**Comment by calvix** [comment]
OK, with `we` I mean team firecracker, but the person who will do that is me :) No worries

**Comment by calvix** [comment]
just small note  to nodepool deletion, it takes forever, not sure what is wrong, we might wanna investigate later

**Comment by xh3b4sd** [comment]
Since we added the cross references for security group ingress rules from and to each Node Pool I noticed cluster deletion became super slow. It takes 1 or 2 hours to delete a cluster for some reason.

**Comment by calvix** [comment]
What I see is that the node Pools instances are stuck in `termination wait` due to lifecycle hook,  We might have check on that what is happening

**Pull request merged**
