### PR TITLE
Fix subnet route table association resource names

### PR DESCRIPTION
**Pull request by tuommaki**
I made a mistake by dropping "Subnet" part from subnets' route table
association resource names and this broke migration path from old
clusters to new clusters.

Towards https://github.com/giantswarm/giantswarm/issues/4792

### CODE REVIEW

**Comment by tuommaki** [comment]
I have successful results from testing on `ginger` but also some suspicious events and I want to give this one more shot before merging. The code is ready for review though.

**Comment by tuommaki** [comment]
> When this works and e2e is happy let's go. What I am wondering is how we missed that with all of our extensive testing upfront.

This is a question I've been wondering as well...

**Comment by tuommaki** [comment]
> When this works and e2e is happy let's go. What I am wondering is how we missed that with all of our extensive testing upfront.

Easy. With a wrong operator version. I just did it myself. Wondering what on earth goes wrong until I realize that I forgot to deploy the right version. This same mistake would explain the earlier results as well. Especially when there were two different environments used back and forth. One could even accidentally deploy the "right" version to wrong environment and happily test with wrong version. When test case is working with single-AZ, you wouldn't notice.

I feel stupid

**Comment by xh3b4sd** [comment]
Is it that you did not deploy what you needed or somebody else overwrote your choice by e.g. merging to master?

**Comment by tuommaki** [comment]
> Is it that you did not deploy what you needed or somebody else overwrote your choice by e.g. merging to master?

In this specific occasion I did not deploy the version needed, but I can imagine that it also happens that deployment gets overwritten while testing (due to merge to `master`) or that one is working a lot on two different environments and accidentally deploys to wrong one.

**Comment by xh3b4sd** [comment]
The latter part should somehow be addressed by something visionary coming from @giantswarm/sig-releng.

**Comment by tuommaki** [comment]
> The latter part should somehow be addressed by something visionary coming from @giantswarm/sig-releng.

My idea to prevent these mistakes (all of them) would be to have an empty cluster as a start state for testing. `kubectl -n giantswarm get pods` returns an empty list, you can't really accidentally fail unless you are fully operating on wrong environments, but that would be a whole new level then. It would help for this though and theoretically could be semi-easily fixed with `opsctl`. We need to discuss about this.

**Comment by tuommaki** [comment]
Ok. Success also with latest test from `5.2.1` -> `6.1.0` & `6.0.0` -> `6.1.0`. Now I'm confident with this.

**Pull request merged**
