### PR TITLE
WIP: Restrict security group rules

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#1497

### CODE REVIEW

**Comment by asymmetric** [comment]
Isn't this what we were doing previously? It won't work unless the network setup change, i.e. if the connection still comes with a public IP, then the SG won't apply.

**Comment by rossf7** [comment]
Yes this is to debug it. I agree I think the problem is the public IP for etcd.

The problem is currently the kubelet ports are unsecured and open. This was temporary just to unblock testing.

**Comment by asymmetric** [comment]
Yes, we should have a meeting to discuss network layout. Is fixing this now a priority? I thought we wanted to do it later.

**Comment by rossf7** [comment]
Security group changes will be done later.

**Pull request closed without merging**
