### PR TITLE
vendor: updated k8scloudconfig

### PR DESCRIPTION
**Pull request by rossf7**

### CODE REVIEW

**Comment by asymmetric** [comment]
Did you run `make update-vendor`?

**Comment by rossf7** [comment]
@asymmetric yes I did that.

**Comment by rossf7** [comment]
Yes it pulled in some more updates but I think that matches our current vendoring approach. I like that we have `make update-vendor`.

**Comment by rossf7** [comment]
@asymmetric because I was lazy and used the web UI. I'll fix.

**Comment by rossf7** [comment]
Closing. Will do fresh vendor PR so we have clean history and can move on with our lives. 😆

**Pull request closed without merging**
