### PR TITLE
do-not-return-deleted-nat-gateways

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/giantswarm/issues/14731
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by calvix** [comment]
tested by creating a cluster, deleting it, and recreating again, everything worked and the deleted NAT gateways wer ignored

**Comment by xh3b4sd** [comment]
Can you elaborate on how you create, delete, create the cluster? I would not know how to even do that. 😅

**Comment by xh3b4sd** [comment]
Also, AFAIK it is more dangerous to create clusters with the same ID twice due to the KMS encryption keys. That could have unintended side effects and we never really did or recommend that.

**Comment by calvix** [comment]
I simply created cluster via `gsctl create cluster`, then waited until cluster was up and ready.

Then dumped all the CRS into YAML file (`AWSCOntrolPlane, G8sControlPlane,AWSCluster,Cluster,AWSMachineDeployment,Machinedeployment`) and removed the weird values like `uuid` `self-link` `creationTimestamp` and so on, and only kept the pure CR data. Also removed `status` field.

Then deleted cluster via `gsctl delete cluster` and waited until the cluster is gone. Checked the AWS console and saw 3 NAT gateways in `deleted` state.

I recreated the cluster with the YAML files I dumped before, which created a cluster with the same IDs.

After that checked logs of `aws-operator` to see that it only found 3 NAT Gateways and that it ignored the deleted ones. Also checked cluster and CloudFormation stacks.

All was green

**Comment by calvix** [comment]
> Also, AFAIK it is more dangerous to create clusters with the same ID twice due to the KMS encryption keys. That could have unintended side effects and we never really did or recommend that.

We do not recommend it but we know customer do it to keep some specific cluster-ID formula, the KMS seems not to be that much problem so far, only the NAT gateways fucked up the CF.

**Review by xh3b4sd — APPROVED** [review]

**Pull request merged**
