### PR TITLE
Do not create Hosted Zones

### PR DESCRIPTION
**Pull request by asymmetric**
Use Hosted Zone IDs from TPO, as their creation is considered part of the manual setup process.

**Note**: I haven't removed the [logic](https://github.com/giantswarm/aws-operator/blob/master/resources/aws/hosted_zone.go) for HZ creation, as I thought we might need it in the future. OTOH we can easily retrieve it from the history if we do. WDYT?

Fixes https://github.com/giantswarm/giantswarm/issues/1491

### CODE REVIEW

**Comment by kopiczko** [comment]
On code removal: I don't have strong opinion.

**Comment by rossf7** [comment]
I think it would be better to remove the hosted zone code. As you say we can get it back from the history if we need it.

**Comment by asymmetric** [comment]
@rossf7 Please feel free to do it if you're free. I'm currently busy with this PR still, as I think I left out some important bits.

**Comment by rossf7** [comment]
@asymmetric Cool, on it :)

**Comment by rossf7** [comment]
@asymmetric LGTM and the kubernetesd change is merged

**Pull request merged**
