### PR TITLE
service: introduce awsconfig package

### PR DESCRIPTION
**Pull request by kopiczko**
Similar to https://github.com/giantswarm/kvm-operator/pull/354

### CODE REVIEW

**Comment by kopiczko** [comment]
Thanks!

**Comment by rossf7** [comment]
For the imports problem its because legacy uses k8scloudconfig v2_0_0 and cloudformation uses k8scloudconfig v3_0_0

I think this structure under awsconfig would work better.

```
service/awsconfig
├── v2
│   ├── cloudconfig
│   │   └── cloudconfigtest
│   ├── key
│   └── resource
│       ├── legacy
├── v3
│   ├── cloudconfig
│   │   └── cloudconfigtest
│   └── resource
│       ├── cloudformation
│       │   └── adapter
│       ├── endpoints
│       ├── kmskey
│       ├── namespace
│       ├── s3bucket
│       ├── s3object
│       └── service
└── v4
    └── cloudconfig
        └── cloudconfigtest
│   └── resource
│       ├── cloudformation
│       │   └── adapter
│       ├── s3object
```

**Comment by kopiczko** [comment]
We will be fixing imports. I don't care about v2 as it is passing away soon :)

**Comment by rossf7** [comment]
OK cool that makes sense. Legacy will be getting deleted soon. Thanks for restructuring. <3

**Comment by xh3b4sd** [comment]
<3

**Pull request merged**
