### PR TITLE
Activate gathering of Cluster CR network allocations in IPAM

### PR DESCRIPTION
**Pull request by tuommaki**
When finding out existing network allocations, gather also ones defined in
Cluster CR objects now that Cluster CRD is registered.

### CODE REVIEW

**Comment by tuommaki** [comment]
Ok. This PR should wait until `clusterapiClusterController` is activated. https://github.com/giantswarm/aws-operator/blob/master/service/service.go#L400

**Comment by xh3b4sd** [comment]
Why? We can just merge it IMO. All good.

**Comment by tuommaki** [comment]
> Why? We can just merge it IMO. All good.

Because otherwise listing `Cluster` CRs fails because CRD isn't registered:
```
W 05/17 07:44:16 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/awsconfigs/446ns ipamv26 retrying due to error | operatorkit/controller/resource/retr
yresource/resource_wrapper.go:74 | controller=aws-operator | event=update | loop=12 | underlyingResource=ipamv26 | version=123178408                           
        /go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/resource_wrapper.go:67:          
        /go/src/github.com/giantswarm/aws-operator/service/controller/legacy/v26/resource/ipam/create.go:76:                                                   
        /go/src/github.com/giantswarm/aws-operator/service/network/allocator.go:54:                                                                            
        /go/src/github.com/giantswarm/aws-operator/service/controller/legacy/v26/resource/ipam/create.go:149:                                                  
        /go/src/github.com/giantswarm/aws-operator/service/controller/legacy/v26/resource/ipam/create.go:136:                                                  
        /go/src/github.com/giantswarm/aws-operator/service/controller/legacy/v26/resource/ipam/create.go:228:                                                  
        the server could not find the requested resource (get clusters.cluster.k8s.io)
```

**Comment by xh3b4sd** [comment]
Can we then just enable the controller? There aren't any CRs anyway.

**Comment by tuommaki** [comment]
> Can we then just enable the controller? There aren't any CRs anyway.

Yes, I think it should be fine.

**Comment by tuommaki** [comment]
Tested on `ginger`. Seems to work as expected.

**Pull request merged**
