### PR TITLE
Disable hyperthreading

### PR DESCRIPTION
**Pull request by MarcelMue**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
What about this bad boy here?

**Comment by MarcelMue** [comment]
@brinker211 is taking care but it takes some time next to SE duties. So please keep around for now.

**Comment by xh3b4sd** [comment]
19 days in. Let's make a move. 🚀

**Comment by brinker211** [comment]
This is on me and sstk right now pending an sstk side investigation. I'll do the needful, thanks.

**Comment by xh3b4sd** [comment]
I am just closing this for now. Feel free to reopen.

**Pull request closed without merging**
