### PR TITLE
Bump k8scc version

### PR DESCRIPTION
**Pull request by Strigix**
Bumping the k8scc version to include changes made to podsecuritypolicies.

### CODE REVIEW

**Review by whites11 — APPROVED** [review]

**Comment by paurosello** [comment]
@Strigix I solved the conflicts as I merged another PR that was updating k8scloudconfig too, which PSP changes are included here? this will be on release 19 I think

**Comment by Strigix** [comment]
@paurosello In the restricted podsecuritypolicy we've allowed all seccompprofiles and set runtime/default as the default seccomp profile for workloads that don't have one specified. 
This is a response to a ticket mentioning Kyverno requires a seccomp profile, but the restricted PSP didn't allow one in the past.

**Comment by T-Kukawka** [comment]
@Strigix can u elaborate on the impact actually? it is just a patch release in k8scc

**Comment by njuettner** [comment]
Closing this PR, I discussed it with Stefan.

**Pull request closed without merging**
