### PR TITLE
Don't update S3 objects in s3objectv2 resource

### PR DESCRIPTION
**Pull request by rossf7**
I added update support when I created the s3object resource but this is incorrect.

We only use the resource for uploading versioned cloudconfigs to S3. Since they are versioned we should only add files to the S3 bucket.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
> We only use the resource for updating versioned cloudconfigs to S3. Since they are versioned we should only add files to the S3 bucket.

I am lost here. Why do we only need to add but not update? Is this some legacy magic for older clusters? Will newer ones be updated?

**Comment by kopiczko** [comment]
> We only use the resource for updating versioned cloudconfigs to S3

I thing updating -> uploading. Correct?

Also `s2objectv2` in the title :D I was wondering what it is for a while ;)

**Comment by kopiczko** [comment]
(I understand the S3 object content is CC)
I don't think updating here is wrong. If version bundles are handled the desired state should be always the same. Unless certificates are rolled, but in that case we should update the object.

**Comment by fgimenez** [comment]
After testing again with merged master all went fine :+1:

**Comment by rossf7** [comment]
Indeed there were 2 typos :( The resource uploads to the S3 bucket.

For keeping updates I see the use case for rolling certificates. But rolling certificates isn't supported currently. I'd prefer to enable updating S3 objects when it's required and has been tested end to end.

**Comment by xh3b4sd** [comment]
> rolling certificates isn't supported currently

The business logic of the operator should ensure that the current state is reliably transitioned towards the desired state. So even if the active certificate rolling is not supported the operator should simply make sure that the state is always the expected one. This implies changing the current state in case the desired state changes. It can just happen that certificates change because they are either expired and thus renewed or the alternative names changed or something like this. In case the operator simply keeps the state up everything should be fine and we do not have to bother about certificate rotation or anything. I am not into all the details with the S3 uploads which is why I ask stupid questions. My only desire is to keep the operators functional in a as nice and clean way as possible.

**Comment by rossf7** [comment]
Rolling certificates via updating k8scloudconfig will be unreliable on AWS as existing workers will not be replaced.

For workers we pass the S3 URL in the small cloudconfig. So when we change the version the cloudconfig changes and a rolling update is triggered. If the certificates change and we update the S3 bucket then new nodes will get the new certificates but old nodes will be unchanged.

This inconsistent state with legacy clusters caused a lot of problems. This is why I think the correct behavior is we always add a new cloudconfig object to the S3 bucket.

**Comment by xh3b4sd** [comment]
> This is why I think the correct behavior is we always add a new cloudconfig object to the S3 bucket.

This implies the following then right? 

> If the certificates change and we update the S3 bucket then new nodes will get the new certificates but old nodes will be unchanged.

If this is still true I am fine with the implementation. I am only interested in the outcome here, not the implementation details. When you think this is the right way to achieve what we want then I am fine with it.

**Comment by rossf7** [comment]
The outcome is to not have cluster nodes with an inconsistent state. This prevents that by ensuring all workers receive the same cloudconfig.

**Comment by xh3b4sd** [comment]
I get the inconsistent state problem but in terms of certificates we should make sure that nodes always get valid certificates. Having a consistent state that uses outdated certs will just make the cluster fail. This is why I think the certs should always be considered on reboot/scaling. The state of the certs is "inconsistent" anyway because every node should have their own certs in theory and the level of consistency should rather be accomplished on having consistently valid certificates than consistent certificate bytes which will just fail eventually.

**Comment by rossf7** [comment]
Yes I get that we should replace with valid certificates if they are available.

Closing so we can move on. We can come back to this later if it causes problems.

**Pull request closed without merging**
