### PR TITLE
Use generated config to deploy aws-operator

### PR DESCRIPTION
**Pull request by kubasobon**
Towards https://github.com/giantswarm/giantswarm/issues/15229

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by corest** [comment]
Is this based on https://github.com/giantswarm/aws-operator/pull/2844 ? So i could close that one

**Review by kopiczko — APPROVED** [review]
LGTM Now we need to teach @giantswarm/team-firecracker-engineers how to use that.

**Comment by calvix** [comment]
how much testing did you put into confirming that all values are properly propagated as before?

**Comment by kopiczko** [comment]
> how much testing did you put into confirming that all values are properly propagated as before?
> How was it tested?

1. Deploy this branch
2. Deploy https://github.com/giantswarm/aws-operator/pull/2946
3. Compare generated CMs and Secrets.

The only differences are expressed there:

```
	devctl replace -i '"InstanceType":' '"instanceType":' $(INSTALLATION)-$(BRANCH).yaml
	devctl replace -i '"WeightedCapacity":' '"weightedCapacity":' $(INSTALLATION)-$(BRANCH).yaml
	devctl replace -i ' CIDR:' ' cidr:' $(INSTALLATION)-$(BRANCH).yaml
```

But microkit is case insensitive.

If you want detailed version:

<details><summary>Makefile</summary>

```makefile
APP := aws-operator
BRANCH := pawel-master
TEST_BRANCH := config-controller-test

KUBECTL := kubectl --context giantswarm-$(INSTALLATION)

clean:
	@[[ ! -z "$(INSTALLATION)" ]] || (echo "Set INSTALLATION" >&2 && exit 1)
	@echo "====> clean"
	@$(MAKE) undeploy-$(APP)@$(BRANCH)
	@$(MAKE) undeploy-$(APP)@$(TEST_BRANCH)

test:
	@[[ ! -z "$(INSTALLATION)" ]] || (echo "Set INSTALLATION" >&2 && exit 1)
	@echo "====> $(INSTALLATION)"
	opsctl create kubeconfig -i $(INSTALLATION) >/dev/null
	@$(MAKE) deploy-$(APP)@$(BRANCH)
	@$(MAKE) deploy-$(APP)@$(TEST_BRANCH)
	@$(MAKE) test-cm
	@$(MAKE) test-secret
	@$(MAKE) clean

deploy-%:
	@echo "====> $@"
	opsctl deploy $* -i $(INSTALLATION)

undeploy-%:
	@echo "====> $@"
	opsctl undeploy $* -i $(INSTALLATION)

test-cm:
	@echo "====> $@"
	# Make Sure CMs exist.
	$(KUBECTL) get cm -n giantswarm $(APP)-$(BRANCH)
	$(KUBECTL) get cm -n giantswarm $(APP)-$(TEST_BRANCH)
	# Get CMs data.
	$(KUBECTL) get cm -n giantswarm $(APP)-$(BRANCH) -o yaml | yq e '.data' - > $(INSTALLATION)-$(BRANCH).yaml
	$(KUBECTL) get cm -n giantswarm $(APP)-$(TEST_BRANCH) -o yaml | yq e '.data' - > $(INSTALLATION)-$(TEST_BRANCH).yaml
	# Make sure there is single key in each CM
	[ $$(yq e 'length' $(INSTALLATION)-$(BRANCH).yaml) -eq 1 ]
	[ $$(yq e 'length' $(INSTALLATION)-$(TEST_BRANCH).yaml) -eq 1 ]
	# Make sure the single key is "config.yaml"
	[ $$(yq e 'del(."config.yaml") | length' $(INSTALLATION)-$(BRANCH).yaml) -eq 0 ]
	[ $$(yq e 'del(."config.yaml") | length' $(INSTALLATION)-$(TEST_BRANCH).yaml) -eq 0 ]
	# Read "config.yaml" key content to avoid string style problems
	yq e -i '."config.yaml"' $(INSTALLATION)-$(BRANCH).yaml
	yq e -i '."config.yaml"' $(INSTALLATION)-$(TEST_BRANCH).yaml
	# Manipulations
	devctl replace -i '"InstanceType":' '"instanceType":' $(INSTALLATION)-$(BRANCH).yaml
	devctl replace -i '"WeightedCapacity":' '"weightedCapacity":' $(INSTALLATION)-$(BRANCH).yaml
	devctl replace -i ' CIDR:' ' cidr:' $(INSTALLATION)-$(BRANCH).yaml
	# Compare
	git --no-pager diff --no-index $(INSTALLATION)-$(BRANCH).yaml $(INSTALLATION)-$(TEST_BRANCH).yaml

test-secret:
	@echo "====> $@"
	# Make Sure Secrets exist.
	$(KUBECTL) get secret -n giantswarm $(APP)-$(BRANCH)
	$(KUBECTL) get secret -n giantswarm $(APP)-$(TEST_BRANCH)
	# Get Secrets exist.
	$(KUBECTL) get secret -n giantswarm $(APP)-$(BRANCH) -o yaml | yq e '.data' - > $(INSTALLATION)-$(BRANCH)-secret.yaml
	$(KUBECTL) get secret -n giantswarm $(APP)-$(TEST_BRANCH) -o yaml | yq e '.data' - > $(INSTALLATION)-$(TEST_BRANCH)-secret.yaml
	# Manipulations
	yq e '."aws-secret.yaml"' $(INSTALLATION)-$(BRANCH)-secret.yaml | base64 -d | sed -E '/^\s+accesskey:/,+2d' | sed 's/hostaccesskey:/hostAccessKey:/' | sed '/^[[:space:]]*$$/d' | base64 -w0 | tee /tmp/$(APP)-secret | sed -e '$$a\'
	yq e --inplace '."aws-secret.yaml" = "'$$(cat /tmp/$(APP)-secret)'"' $(INSTALLATION)-$(BRANCH)-secret.yaml
	@# Add a new line at the end.
	yq e '."dockerhub-secret.yaml"' $(INSTALLATION)-$(BRANCH)-secret.yaml | base64 -d | sed -e '$$a\' | base64 -w0 | tee /tmp/$(APP)-secret | sed -e '$$a\'
	yq e --inplace '."dockerhub-secret.yaml" = "'$$(cat /tmp/$(APP)-secret)'"' $(INSTALLATION)-$(BRANCH)-secret.yaml
	rm /tmp/$(APP)-secret
	# Compare.
	git --no-pager diff --no-index $(INSTALLATION)-$(BRANCH)-secret.yaml $(INSTALLATION)-$(TEST_BRANCH)-secret.yaml
```

</details>

**Comment by kopiczko** [comment]
BTW. Tested on all AWS installations.

**Comment by calvix** [comment]
if get the testing right, you deploy aws-operator the old way and than with the config controller and than download the configmaps for aws-operator, replace 3 values and compare them and they are equal?

ok that sounds foolproof :)

**Comment by kubasobon** [comment]
> Is this based on #2844 ? So i could close that one

Yes, I've cherry-picked from #2844 and #2924.

**Comment by calvix** [comment]
what changes has to be done once this is merged? is there anything we need to take care or everything will work as it works now?

We have a release 14.0.0 WIP and need to add one bugfix and than ship it, so don't want to hit some wall on the way

**Comment by njuettner** [comment]
Does this has effect for the aws-admission-controller? We use some of those changed config names also here https://github.com/giantswarm/aws-admission-controller/blob/master/helm/aws-admission-controller/templates/deployment.yaml#L35-L58?

**Comment by kopiczko** [comment]
> what changes has to be done once this is merged? is there anything we need to take care or everything will work as it works now?

We need to release giantswarm/config v1.0.0 and merge this. Then since CM and Secret are exactly the same (besides some small string case differences) we are pretty sure everything will work as it does now.

> Does this has effect for the aws-admission-controller? We use some of those changed config names also here https://github.com/giantswarm/aws-admission-controller/blob/master/helm/aws-admission-controller/templates/deployment.yaml#L35-L58?

I'd be surprised if it does. We did it in a way so giantswarm/installations and giantswarm/config values render the same  CM and Secret.

**Review by calvix — APPROVED** [review]

**Review by njuettner — APPROVED** [review]
Ok :)

**Pull request merged**
