### PR TITLE
update ami list

### PR DESCRIPTION
**Pull request by ericgraf**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by ericgraf** [comment]
Ran `devctl gen ami --dir service/controller/key` to generate the list of ami's . There are a few ami's that look to be deleted.   
@giantswarm/team-firecracker  WDYT ?

**Comment by njuettner** [comment]
AMI's from China should not be deleted. You also need to find the ID's in `aws-china` manually for the 2 regions `cn-north` and `cn-northwest`. The reason is the are set `private` IIRC, that's why it cannot found those AMI's.

**Comment by ericgraf** [comment]
@njuettner Fixed and added the two for cn-north-1 and cn-northeast-1.

**Review by calvix — APPROVED** [review]
lgtm

**Review by njuettner — APPROVED** [review]
🚀

**Review by MarcelMue — APPROVED** [review]

**Comment by calvix** [comment]
shall we merge?

**Comment by MarcelMue** [comment]
I just did it for @ericgraf :D

**Pull request merged**
