### PR TITLE
Disable hostedzone resource in v12 to fix cluster creation problems

### PR DESCRIPTION
**Pull request by rossf7**
Hosted zone resource is causing problems with cluster creation because its looking up hosted zones that don't exist. Disabling it as it isn't needed until BYOC changes are enabled in later resource sets.

### CODE REVIEW

**Comment by rossf7** [comment]
We didn't see this in our AWS account because its looking up a hosted zone `ginger.eu-central-1.aws.gigantic.io.` that exists in the correct AWS account. In other installs with custom DNS this is not the case.

I agree we can't break master like this.

**Comment by rossf7** [comment]
Also disabling the migration resource because its erroring.

```
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:313","event":"update","level":"error","message":"stop reconciliation due to error","object":"/apis/provider.giantswarm.io/v1alpha1/namespaces/default/awsconfigs/82t4o","stack":"[{/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:436: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/metricsresource/resource_wrapper.go:48: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/resource_wrapper.go:79: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/resource_wrapper.go:67: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v12/resource/migration/resource.go:92: } {Operation cannot be fulfilled on awsconfigs.provider.giantswarm.io \"82t4o\": the object has been modified; please apply your changes to the latest version and try again}]","time":"2018-06-13T12:51:50.937217+00:00"}
```

**Comment by rossf7** [comment]
@xh3b4sd I think your idea on feature flagging is good. I think we could only enable major changes like this on our installations until we're ready to roll out to all installs.

**Comment by xh3b4sd** [comment]
Yes but the feature flipper wouldn't have caught the issue with a production environment in which settings are just different. This is tricky to catch with QA upfront.

**Comment by rossf7** [comment]
Tested on `ginger`. Going with this because its just disabling code.

**Comment by kopiczko** [comment]
cc @giantswarm/team-magic 

What is the example hosted zone that doesn't exist?

**Comment by rossf7** [comment]
@kopiczko It was in `viking`.  I'll ping you in the postmortem.

**Pull request merged**
