### PR TITLE
update architect orb

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Comment by kopiczko** [comment]
I see https://github.com/giantswarm/giantswarm/issues/7485#issuecomment-587441990

**Comment by mig4** [comment]
Hi @xh3b4sd, just wanted to check, is this waiting for something or is it ready to go? If it's OK to go ahead but you don't have time, mind if I take over? I'm working on giantswarm/giantswarm#8637 and need to update architect-orb to 0.6.0 for that.

**Comment by xh3b4sd** [comment]
The problem here is that the orb version I wanted to use requires go-modules which we do not use here yet. Thomas worked on an orb version for dep projects but I am not sure what the state is with that. I would actually close this PR. If you want to take it over and do your thing feel free to go ahead. Otherwise let me know and I close this PR.

**Comment by mig4** [comment]
Oh right, I was wondering why most operators still use the `architect` binary instead of the orb, that explains it. OK I'll play around with it, possibly revert to using `architect` for now but keep the import fixes, etc. Thanks!

**Comment by mig4** [comment]
Right, in the end since current build always picks up the latest `architect` and that already contained the changes I needed, I just went with it for now. So I guess this can be closed, unless you think there's value in separating out the import ordering and submitting that? But I guess we'll get to it one way or another.

**Pull request closed without merging**
