### PR TITLE
awsconfig/v7: vendor priority classes

### PR DESCRIPTION
**Pull request by corest**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
FYI I merged master for you in here.

**Comment by kopiczko** [comment]
v7 was released today.

**Comment by corest** [comment]
With cloudconfig WIP and probably not vendored dependencies

**Comment by xh3b4sd** [comment]
> With cloudconfig WIP and probably not vendored dependencies

What does that mean? Anything that goes to master has to be releasable all the time because the merge into master is in fact the process of releasing. That we have versioning does not mean we can merge just anything to master and be fine with it being broken. Us having versioning means having more control about what and how we give something to customers but that does not mean we can just release a broken state.

**Comment by corest** [comment]
We are not vendoring every change in cloudconfig into all operators every time. I do not avoid my responsibility, but what if I would have a holiday? We need some release procedure here, which will prevent changes to be freezed on the day someone decides to feeze them.

**Comment by xh3b4sd** [comment]
> We are not vendoring every change in cloudconfig into all operators every time.

I think this is the problem. We should actually do that. 

> I do not avoid my responsibility, but what if I would have a holiday?

When you are on holiday you do not work so nothing moves forward or can go wrong with the things you work on, because you are on holiday and do not work on them. 

> We need some release procedure here

IMO the procedure is that everybody working on something makes sure the state in master can be released all the time and whoever wants to release something can just do that without asking for permission any time.

**Comment by corest** [comment]
As I wrote in slack, the problem is missing release management procedure for k8scloudconfig. aws-operator awsconfig was released without freezing cloudconfig release state. 
We mark as WIP cloudconfig version, which is not used in active releases. So, before releasing any operator, which resources use WIP cloudconfig - we need to freeze it and remove WIP label. Also, in this case - who is responsible to lock config resources in other operators? E.g. - after aws-operator starts to use last cloudconfig - other operators also need to start using it, right? So, that means, ebs volume encryption in AWS triggers locking of resources configs in other operators? And there are many more questions

**Comment by xh3b4sd** [comment]
IMO all this is defined and people "just" have to do it. Somebody working on the CC templates has to get it into operators. This includes freezing the templates version at some point. The best point is as we see to freeze it right aways and prevent keeping it open for too long, what we just did here. I think it is ok to keep a WIP version open if everybody is aware of it and fine with it but we just saw that this can become a problem so we should all WIP versions just make as short lived as possible and then we only release stable stuff that can always be activated for the customer. 

When you think there is some guideline missing or there are even more questions please create an issue in which we can discuss the topic with a broader audience to get some wiki pages improved or created. Also write down all your questions there.

**Pull request closed without merging**
