### PR TITLE
Disable anonymous

### PR DESCRIPTION
**Pull request by jgsqware**
Related to this: https://github.com/giantswarm/giantswarm/issues/2020 & https://github.com/giantswarm/k8scloudconfig/pull/224

Update k8sCloudConfig to disable anonymous access to kubernetes api

Closes https://github.com/giantswarm/giantswarm/issues/2020

### CODE REVIEW

**Comment by rossf7** [comment]
Has this been tested on gauss?

**Comment by jgsqware** [comment]
Yes and successful

**Comment by jgsqware** [comment]
Will not merge as the after retesting, cluster is not accessible.

**Comment by jgsqware** [comment]
Was merged with another PR

Cleaning this

**Pull request closed without merging**
