### PR TITLE
Update giantswarm/k8scloudconfig

### PR DESCRIPTION
**Pull request by mazzy89**
This branch updates the giantswarm/k8scloudconfig package. Further we'll use to run e2e tests and hunt the issue reported by @xh3b4sd as in here https://gigantic.slack.com/archives/C7865GLSY/p1549976606014800

### CODE REVIEW

**Comment by mazzy89** [comment]
Though half of the e2e tests fail, the error reported above has not been encountered. In no artifacts, the error shows. I'll give another full run hoping to be luckier.

**Comment by mazzy89** [comment]
After two or three full runs of e2e (honestly I lost even the count 🤯) the error in here https://gigantic.slack.com/archives/C7865GLSY/p1549976606014800 has not been encountered. We can still merge this because it anyways enriches the error reporting with the stack trace. 

However, this still leads us to the unresolved topic discussed here https://github.com/giantswarm/aws-operator/pull/1404. The ultimate goal is to have a good sample which is a certificate to kick off a test case and reproduce the issue. So as next let's merge this PR and if the error does not appear in any case, let's move ahead.

**Comment by xh3b4sd** [comment]
I would say keep it running until we find it. You do not have to watch it all the time. You can do something else meanwhile.

**Comment by mazzy89** [comment]
Despite the undoubted beauty of our e2e tests, I definitely like watching all the time something else 😄😎

**Comment by mazzy89** [comment]
During the last run of e2e tests - `e2eTestWIPPRScaling` we got finally something:

From https://16852-80619275-gh.circle-artifacts.com/0/logs/giantswarm-aws-operator-7679459686-vv6gh-logs.txt the error below is all over the place.

```json
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:358","controller":"aws-operator","event":"update","level":"error","loop":"5","message":"stop reconciliation due to error","object":"/apis/provider.giantswarm.io/v1alpha1/namespaces/default/awsconfigs/ci-wip-d185d-5e958","resource":"s3objectv23","stack":"[{/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:518: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/metricsresource/crud_resource_wrapper.go:62: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/crud_resource_wrapper.go:81: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/crud_resource.go:89: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/metricsresource/crud_resource_ops_wrapper.go:70: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/crud_resource_ops_wrapper.go:102: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/crud_resource_ops_wrapper.go:89: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v23/resource/s3object/desired.go:100: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v23/resource/s3object/desired.go:65: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v23/cloudconfig/master_template.go:81: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/cloudconfig.go:75: } {template: cloudconfig:508:23: executing \"cloudconfig\" at \u003c.Extension.Files\u003e: error calling Files: template: :1: unexpected expected := in command}]","time":"2019-02-14T16:28:06.460513+00:00","version":"652"}
```

Same area that is an issue in rendering the template. Tough is pretty different from the reported one initially:

```json
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/crud_resource_ops_wrapper.go:96","controller":"aws-operator","event":"update","function":"GetDesiredState","level":"warning","loop":"15","message":"retrying due to error","object":"/apis/provider.giantswarm.io/v1alpha1/namespaces/default/awsconfigs/ci-wip-5ba69-5e958","resource":"s3objectv22","stack":"[{/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/crud_resource_ops_wrapper.go:89: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v22/resource/s3object/desired.go:100: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v22/resource/s3object/desired.go:65: } {/go/src/github.com/giantswarm/aws-operator/service/controller/v22/cloudconfig/master_template.go:81: } {template: cloudconfig:508:23: executing \"cloudconfig\" at \u003c.Extension.Files\u003e: error calling Files: template: :2: unexpected bad character U+001D in command}]","time":"2019-02-12T12:13:55.461191+00:00","underlyingResource":"s3objectv22","version":"1035"}
```

The interesting thing is that it happens in the same e2e test case which is the scaling one - `e2eTestWIPPRScaling`. Further, it is not clear how/when the error is raised. It appears under complete indeterminate circumstances during the scaling phase.

**Comment by xh3b4sd** [comment]
Do we have the content we need now to create a unit test?

**Comment by mazzy89** [comment]
I haven't found assets because (guessing) purged after e2e tests completed. Beside logging the contents of assets and then look for them in the e2e logs, any quick hints/workaround to make stay the assets after the e2e are completed?

**Comment by xh3b4sd** [comment]
A couple of days ago we said we can log the content. Did you not log the content now? Why did you run the tests if you did not log them as we agreed on?

**Comment by mazzy89** [comment]
I don't recall now that agreement, sorry. I wish to work on the entire assets having them accessible on the current backend for instance S3 rather than start to log everything. It's a more viable solution because if we have everything accessible we can easily discover there what is going on instead to log and hopefully find what we are looking for and then if we haven't found it, running again the tests which take time. So back to the question. Is there a way to prevent assets to be removed after the e2e fails like an env var to control or a flag? If not then I'll go with the hard way 😞

**Comment by xh3b4sd** [comment]
Ok, but how do you run the tests and wait another one or two days when there are still no results yet? For me it would have been easy to log the asset content. You can maybe disable the cluster deletion in the e2e tests and keep the assets that way but it might be that you only get the encrypted content and I cannot tell you how to tweak the e2e setup from the top of my head. So what you want to do is the hard way for me.

**Comment by mazzy89** [comment]
> but how do you run the tests and wait another one or two days when there are still no results yet?

The assumption wrong from my side was to assume to find the assets still in place even when e2e failed. I was still attached to my past experiences where failed e2e tests stored all the artifacts produced in the area ready to be explored later.

At this point, I think I'll follow your recommendation and log as much as I can on the template part to grab as much as information possible. 

Thank you @xh3b4sd to be so patient and proactively reply to this 😉

**Comment by xh3b4sd** [comment]
No worries. The communication is pretty important in a remote setting. Quick feedback loops. Past has shown that it is not good to ponder on issues alone for days. Let's just hang and talk when there is anything weird. We work on the PM for over two weeks now and it would be good to get over it.

**Comment by mazzy89** [comment]
I've run plenty of times the e2e tests in the last 72 hours looking for the cloud-config error in the logs. Despite the countless times the e2e have run, I haven't found that issue reported in any logs. 

At this point, I'm wondering if it still really makes sense to continue with this hunt. The observation cases are absent, and naturally, without them, it's tough to validate our hypothesis. 

Further the issue as long as I know, it has not been encountered anymore in any clusters. Nevertheless, even when the problem could unexpectedly appear during one sporadic run, then it would not prove that much because it's nature completely indeterministic make it very hard to place in a precise execution context.

**Comment by mazzy89** [comment]
It is closing for now due to the lack of observability and reproducibility of the issue. No element has been found in the last days to corroborate the initial hypothesis. We'll get back here in case it is again found.

**Pull request closed without merging**
