### PR TITLE
Add cni internalelb

### PR DESCRIPTION
**Pull request by paurosello**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by paurosello** [comment]
I also created this branch to fix this to 9.3.X https://github.com/giantswarm/aws-operator/tree/93x-fixinternalelbcni but not sure if we make the release based on that or we merge it somewere

**Review by calvix — APPROVED** [review]
lgtm if tested

**Comment by xh3b4sd** [comment]
What is the background for this change? Do we enable a feature or fix a bug?

**Comment by paurosello** [comment]
Yeah, should have mentioned this change is done for https://github.com/giantswarm/giantswarm/issues/15298

**Comment by paurosello** [comment]
I was not able to test the whitelisted option (apart from the golden files). Do we have any of our installation whit whitelisted API?

**Comment by calvix** [comment]
> I was not able to test the whitelisted option (apart from the golden files). Do we have any of our installation whit whitelisted API?

I think ginger has the API whitelisted

 so testing it works on both gauss and ginger should be the goal

**Comment by paurosello** [comment]
Tested on gauss and ginger, all good!

**Pull request merged**
