### PR TITLE
awsconfig/v5: update imports and packages

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#2544

### CODE REVIEW

**Comment by rossf7** [comment]
@kopiczko Docs worked great just hit 2 issues.

- Updating the resource names which we know about.
- I was using the crappy mac sed and it renamed files to `.go-e` and even `.go-e-e`.

Switching to `gsed` which I have installed via brew fixed it. I'm going to switch my `sed` to `gsed` but I think its worth mentioning in the docs.

**Comment by xh3b4sd** [comment]
Yeah, I would still favour having this in opsctl or something. Letting everybody have its own script will just be awful in the future. Having a common cross platform binary is the way to go in the long run IMO.

**Comment by kopiczko** [comment]
@rossf7 thanks for the feedback. I updated the wiki about gsed. https://github.com/giantswarm/giantswarm/wiki/Releases:-Creating-New-VersionBundle#macos-users-only

Naming issue isn't straight forward to resolve I'll have to think about it. E.g. can't blindly replace `v1` with `v2` otherwise we'll mess with kubernetes imports.

**Comment by kopiczko** [comment]
@xh3b4sd I think everybody agrees having a binary is just better.

**Comment by rossf7** [comment]
@kopiczko Thanks for updating the docs. Cool, I'll just merge imports PRs in future.

I think developing a first version in bash and converting to Go later is a good approach.

**Pull request merged**
