### PR TITLE
vendor: Use kubernetes-1.15.4

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#6302

### CODE REVIEW

**Comment by rossf7** [comment]
Tested on `ginger` but e2e is red and I don't want to deploy this late on a Friday.

**Comment by MarcelMue** [comment]
What is the status here? With more changes in aws-operator this will create some merge conflicts.

Can we help here somehow? cc @tfussell

**Comment by rossf7** [comment]
@MarcelMue Yes this is the last PR to complete the deps upgrade.

@sslavic Is working on this and is trying to get e2e green. But that is a big task and I agree keeping the PR open will cause issues.

IMO we should merge the e2e fixes we're confident on and continue fixing e2e in separate PRs. I manually tested cluster creation on Friday and it was fine.

Stevo, WDYT?

**Comment by sslavic** [comment]
Breaking this one down into separate smaller PRs.

**Comment by sslavic** [comment]
@rossf7 IMO this one is ready to be merged and deployed. PTAL

**Pull request merged**
