### PR TITLE
Improve logging for shouldScale method

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/3489

Improves logging to identify scaling problems more easily.

For the linked postmortem the cluster was not scaled because the cloud formation output for the master k8scloudconfig did not match the desired state. The cluster was not updated because the version bundle version did match.

The log message was

`the guest cluster main stack does not have to be scaled`.

Even though the worker count had changed. With this change the reason for not scaling will be logged.

I did think about erroring in this case but I don't think that is possible because there could be a stack update in progress.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Just saying that the issue with the broken update does not lay in the method we debug here more. There got some state transitioning broken before. I also want to add that this is something we are going to address better in general in the future. We now have the versions in the guest cluster node labels and thus have the real and definite relationship between the node state and the version it represents. The update mechanism has to be reworked to make use of this and then the broken state bullshit that happened in the incident cannot happen anymore in such a mystical way.

**Comment by rossf7** [comment]
Yes totally, this doesn't fix the issue but it does improve the logging so its easier to diagnose what is going wrong.

I like the approach with the node labels. Is there an issue for fixing the state transitioning?

**Comment by xh3b4sd** [comment]
There is no explicit issue but I track it with the update story and the CR status stuff we need for e2e tests. This is all interconnected and I just do it along there.

**Comment by rossf7** [comment]
Ack. Makes sense to handle as part of the update story. Thx for the info.

**Pull request merged**
