### PR TITLE
service: remove ProxyProtocol on IC ELB

### PR DESCRIPTION
**Pull request by asymmetric**
it broke stuff

### CODE REVIEW

**Comment by asymmetric** [comment]
@calvix @puja108 @rossf7 any idea if we actually need this?

**Comment by puja108** [comment]
Currently with ELB having it on and not having it as a flag in IC it works, we could try turning it off in ELB too and see if ingress still works, but I wouldn't give it any prio.

**Comment by xh3b4sd** [comment]
What about this PR? Is it still relevent? Should we close it?

**Comment by puja108** [comment]
I guess we can close, reopen (or do new) if needed

**Pull request closed without merging**
