### PR TITLE
Fix encryption certificates

### PR DESCRIPTION
**Pull request by mazzy89**
This PR aims to resolve the issue https://github.com/giantswarm/giantswarm/issues/5179

During cluster creation an error is reported that both master and worker templates are invalid due to unrecognised characters.

The issue is that when the certificates are encoded in base64 with the function `RenderFileAssetContent` then the result is not valid.

The solution resides on encoding in base64 directly rather than passing the asset content to the function.

The questions we could try to reply to make things clear are:

1. Why this issue now? Why has not been found out before? Any regression in any library or any changes?
2. Why the function `RenderFileAssetContent`? The creation of the template invalidates in case of certs breaks the the certs?

cc @corest

### CODE REVIEW

**Comment by corest** [comment]
Pls fix `fmt`. 
The issue is, that encrypted certificate is not a valid go template. But it shouldn't even go through templating as it is for sure doesn't require any

**Comment by mazzy89** [comment]
@corest the `fmt` is already fixed. VSCode has `fmt` included.

> The issue is, that encrypted certificate is not a valid go template. But it shouldn't even go through templating as it is for sure doesn't require any.

Then it makes sense. Even tough I'd expect the template function to be a bit more robust and validate the sanity of the template at the level.

**Comment by mazzy89** [comment]
Yeah good point @corest. Should I make a copy of the v22 folder rename it v22patch and then put the changes there right?

**Comment by corest** [comment]
@mazzy89 no, `v22` is not a part of any active release. But `v21` is. So we will need this in `v22` as well as in `v21patch1`. Or maybe we can even patch it in place.   I think you can ask your buddy about the current release process. Otherwise, I can explain it to you in the call. But all release magic requires time, so you can discuss priorities and process with your team

**Comment by mazzy89** [comment]
@corest gotcha. thank you. I'll ask then to @calvix

**Comment by mazzy89** [comment]
e2e failed 😫let's go to debug again

**Pull request merged**
