### PR TITLE
Reduce scope of tenant policy

### PR DESCRIPTION
**Pull request by pipo02mix**
Some customers would like to have a more tailored policy. In this first step, the goal is to reduce the  scope of the IAM permissions

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Is this PR still relevant?

**Comment by pipo02mix** [comment]
yes it is, but it is not high prio in my list. I will try to tackle this week and I need to add a permission to the policy

**Comment by xh3b4sd** [comment]
I am not really aware of how or where this policy file is being used so I requested review from Vaclav. Please also check CI, the Aliyun push is broken. Shouldn't be related but you never know.

**Comment by pipo02mix** [comment]
This policy is used for the aws operator and admin roles to manage AWS resources

**Comment by xh3b4sd** [comment]
Sure, but where, how and when?

**Comment by pipo02mix** [comment]
1) For aws operator we used when we instance the was clients, so we can perform actions against the AWS API

2) For admin staff we do each time we switch role form our account to customer account to debug or check anything on the cloud provider

**Comment by anvddriesch** [comment]
I don't see anything wrong but not confident to approve this since I don't know much about IAM.

**Pull request merged**
