### PR TITLE
Backporting node termination fix

### PR DESCRIPTION
**Pull request by mazzy89**
Backport node termination fix already in `v24` to `v22patch1` and `v23patch1`.

The resources created are:

* workerasgname
* stackoutput

https://github.com/giantswarm/giantswarm/issues/5382

### CODE REVIEW

**Comment by mazzy89** [comment]
Lots of tests failed. going to check it

**Comment by mazzy89** [comment]
@xh3b4sd e2e tests for the WIP versions are failing. I've tried multiple time but still fails. I'm testing that the backporting works. By checking tests like `e2eTestCurPRClusterState`, `e2eTestCurPRDraining`, `e2eTestCurPRScaling`, `e2eTestCurPRUpdate` can I conclude that the backporting is successfully?

**Comment by xh3b4sd** [comment]
I cannot get the tests green for days either. I had to test more manually. You can do the same. There are also a couple of issues causing cluster creation to break randomly. We have PMs for them.

**Comment by mazzy89** [comment]
I see. thank you for the follow up.

Also, I'm wondering how can I test the patched bundles if the release is not available in the installations?

**Comment by xh3b4sd** [comment]
You can make them available in your test installation.

**Comment by mazzy89** [comment]
Tested manually and it works.

**Pull request merged**
