### PR TITLE
[WIP] Make worker node work

### PR DESCRIPTION
**Pull request by nhlfr**

### CODE REVIEW

**Comment by nhlfr** [comment]
This branch is working - it means, you can deploy mostly working k8s cluster

```
core@master-1 ~ $ ./kubectl run nginx --image=nginx
core@master-1 ~ $ ./kubectl get pods
NAME                    READY     STATUS    RESTARTS   AGE
nginx-701339712-6w7xf   1/1       Running   0          1m
core@master-1 ~ $ ./kubectl exec -ti nginx-701339712-6w7xf bash
root@nginx-701339712-6w7xf:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  31872  5068 ?        Ss   15:37   0:00 nginx: master p
nginx        7  0.0  0.0  32260  2932 ?        S    15:37   0:00 nginx: worker p
root         8  0.0  0.0  20040  2860 ?        Ss   15:38   0:00 bash
root        18  0.0  0.0  20224  3040 ?        Ss   15:39   0:00 bash
root        24  0.0  0.0  17500  2124 ?        R+   15:39   0:00 ps aux
```

**Comment by nhlfr** [comment]
Will do the proper PR-s now.

**Comment by asymmetric** [comment]
@nhlfr should this be closed then?

**Comment by nhlfr** [comment]
I don't know. Making that properly will take at least a week. Maybe let's leave this to let people know which branch to use.

**Comment by nhlfr** [comment]
Please don't delete the branch

**Pull request closed without merging**
