### PR TITLE
Only return running or pending NAT GWs

### PR DESCRIPTION
**Pull request by yasn77**
If cluster ID is reused in quick succession (after deleting), it is possible
that a deleted NAT GW is returned. This commit, adds the state of the NAT GW to
the filter, so that only running and pending NAT GW are returned.

This fixes https://github.com/giantswarm/giantswarm/issues/11727

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Cluster IDs must not be reused due to KMS key issues. It would be news to me if that would work at all. If the proposed change makes sense regardless from an operational point of view can probably better be answered by @calvix.

**Comment by calvix** [comment]
indeed,  reusing cluster ID in a very short time is probabbly going to cause issues due to KMS which stays there in deleting state for quite long time

but I think this is for NodePool creation not cluster and Ia m not sure if we create a unique KMS per NodePool or if we have same  for whle cluster

**Comment by yasn77** [comment]
I wasn't aware of the KMS issue, good to know.

I guess part of the concern is, that using CAPI to create the cluster, there isn't really a guard to stop you from reusing the cluster ID and it's not immediately clear that dangling references in AWS still exist. 

IMHO, at least adding an additional filter that only returns `running` or `pending` should be for lookups.

**Comment by paurosello** [comment]
Not only KMS, S3 also uses the clusterid and takes arround 30 min to fully free (and S3 limitation is across installations)

**Comment by calvix** [comment]
yeah this is not stopper for the PR, but its necessary to be aware of that AWS limitations

**Comment by xh3b4sd** [comment]
Given we are doing final HA Master testing, do we want to risk further issues by merging this to the master branch and release it with our HA Master feature?

**Comment by yasn77** [comment]
> Given we are doing final HA Master testing, do we want to risk further issues by merging this to the master branch and release it with our HA Master feature?

I am happy for this to sit on the back burner... 

I would prefer to keep this open but I'll let you guys decide.

**Comment by marians** [comment]
Sine HA masters is released, are you going to pursue this @yasn77 ?

**Comment by yasn77** [comment]
> Sine HA masters is released, are you going to pursue this @yasn77 ?

Yeh, I'll test this today in a cluster and also fix conflicts.

**Comment by xh3b4sd** [comment]
Checking in again. Anything we can do to get this out of the door?

**Comment by yasn77** [comment]
> Checking in again. Anything we can do to get this out of the door?

Yeh, sorry guys... I've been wanting to test this (more so I know how to do it), but been pretty busy with SE tasks. 

I'll try and get around to this ASAP

**Comment by calvix** [comment]
Can we move on with this somehow?

**Comment by yasn77** [comment]
I am going to close this issue... I just haven't had time to test this out (which I want to do, just from an experience perspective). Since it's not a major issue, i guess it can be looked at, at a later date.

Thanks for input peeps.

**Pull request closed without merging**
