### PR TITLE
enable e2e bastion host

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Huhuuuhuuuuuu, the current build looks pretty goohoooood. 🙈

**Comment by calvix** [comment]
> Huhuuuhuuuuuu, the current build looks pretty goohoooood. see_no_evil

:) lets see, i will do another round and if both of them are green that is a good sign

**Comment by xh3b4sd** [comment]
> There was an issue while running this container and it was rerun. The most recent run is shown.

Circle just crushed your dream. 

It also looks like that the "re-create cluster tests" take super long. Maybe a candidate to investigate.

**Comment by calvix** [comment]
:( the error happened during deletion, so the test was "green" but it timed out during deletion

**Comment by xh3b4sd** [comment]
I think this is something we can then sort separately. When we found problems and solutions we should get them in properly and iterate further from here. Do you provide `k8scloudconfig` PRs?

**Comment by calvix** [comment]
Yes there are three things:
* fix etcd units - k8scloudconfig
* fix tls decrypt script - aws-operator
* i would also recommend disable update-engine on bastion hosts as we do that in k8s-cloudconfig

I can take care of the first 2, maybe even the third if you point me where we build ignition for bastions

**Comment by xh3b4sd** [comment]
All bastion specific code is in https://github.com/giantswarm/aws-operator/blob/master/integration/setup/bastion_instance.go. There is a really ugly multi line string configuration for the ignition config which you probably can simply update accordingly. I have a TODO on my list to gather the SSH users from the installations repo. Right now this is only copy/paste. Fine for now, but I would like to make this better later. 

I would then comment the e2e bastion initialization again, clean vendor and merge this PR. In a next round we can then see what to improve further. Maybe just in two weeks again when there is SIG RelEng SWH again.

**Comment by calvix** [comment]
add retry logic to tls decrypt assets as if the image fetch fails at first try this  was broken

also vendor update of improved k8scloudconfig

**Comment by xh3b4sd** [comment]
> also vendor update of improved k8scloudconfig

How so? The lock file is not updated.

**Comment by calvix** [comment]
> > also vendor update of improved k8scloudconfig
> 
> How so? The lock file is not updated.

Yeah, sorry just vendored via custom branch and not pushed lock file, want to test the k8scloudconfig to ensure all is good and i have not made a mistake

**Comment by calvix** [comment]
looks like its the same result again, the rest of test are always green but the 2/3 can be red because of deletion, so i feel like this si mergable

**Comment by xh3b4sd** [comment]
Makes total sense. We can sort the deletion separately. Thank you for all your support here. ❤️

**Comment by xh3b4sd** [comment]
Note that I moved your fixes to the clusterapi controller. We need to maintain changes there always when we do changes in the legacy controller.

**Comment by calvix** [comment]
> Note that I moved your fixes to the clusterapi controller. We need to maintain changes there always when we do changes in the legacy controller.

right, did not realized that :)

**Pull request merged**
