### PR TITLE
service: put policy/role code in a better place

### PR DESCRIPTION
**Pull request by iaguis**
It has nothing to do with encoding TLS assets.

This prepares the code for uploading cloudconfig to S3.

Depends on #34

### CODE REVIEW

**Comment by nhlfr** [comment]
I'd suggest to create a new file for policy/role. The `service.go` is huge and I think that we should try to move the things out from it.

**Comment by iaguis** [comment]
> I'd suggest to create a new file for policy/role. The service.go file is huge and I think that we should try to move the things out from it.

👍 Yeah, especially because the policies/roles are's gonna grow for the S3 support.

**Comment by xh3b4sd** [comment]
I have no strong feelings about these code moves. I think we should aim for a logical structure that is reasonable. What that means can be decided by you guys.

**Comment by iaguis** [comment]
Updated.

**Pull request merged**
