### PR TITLE
vendor: update

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Can we close this here?

**Comment by kopiczko** [comment]
Yes. I thought it's something else when I looked at the title. Thanks!

**Comment by kopiczko** [comment]
Yes. I thought it's something else when I looked at the title. Thanks!

**Comment by kopiczko** [comment]
Yes. I thought it's something else when I looked at the title. Thanks!

**Comment by kopiczko** [comment]
Yes. I thought it's something else when I looked at the title. Thanks!

**Comment by kopiczko** [comment]
Yes. I thought it's something else when I looked at the title. Thanks!

**Pull request closed without merging**
