### PR TITLE
Update flatcar AMIs

### PR DESCRIPTION
**Pull request by MarcelMue**
Add flatcar AMIs by running `devctl gen ami` to generate the latest flatcar AMIs.

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by xh3b4sd** [comment]
Can we get some description on how you did it? Somebody reading the PR may just wonder how all the information came to be.

**Comment by MarcelMue** [comment]
> Can we get some description on how you did it? Somebody reading the PR may just wonder how all the information came to be.

The first line of the file and the readme contains all info IMO: https://github.com/giantswarm/aws-operator#node-vm-images-amis

**Review by njuettner — APPROVED** [review]

**Comment by xh3b4sd** [comment]
I know how to get the information I need. I think it would just be cool to have at least a single sentence in the PR description because this here is an open source project. I think this is kind of best practice. And I know I also do not always properly do it myself everywhere all the time. Just tried to raise the bar. 🙈

**Review by stone-z — APPROVED** [review]

**Comment by MarcelMue** [comment]
Stale, closing

**Pull request closed without merging**
