### PR TITLE
service: move accountid, credential, locker to internal

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/7345

This is a final touch PR grouping internal packages of the `service` package.

In this batch:

- `service/accountid` package is moved to `service/internal/accountid`
- `service/credential` package is moved to `service/internal/credential`
- `service/locker` package is moved to `service/internal/locker`

There are no changes inside the packages whatsoever.

Final directory structure:

```
./service
├── collector
├── controller
│   ├── controllercontext
│   ├── internal
│   │   ├── adapter
│   │   ├── changedetection
│   │   ├── cloudconfig
│   │   ├── cloudformation
│   │   ├── ebs
│   │   ├── encrypter
│   │   ├── templates
│   │   └── unittest
│   ├── key
│   └── resource
│       ├── accountid
│       ├── ...
│       └── tcnpoutputs
└── internal
    ├── accountid
    ├── credential
    └── locker
```

### CODE REVIEW

**Comment by tfussell** [comment]
What is the point of the `internal` directory? Do those packages differ from the non-internal ones in a particular way?

**Comment by kopiczko** [comment]
> What is the point of the `internal` directory? Do those packages differ from the non-internal ones in a particular way?

Yes - they should not be imported outside the parent package. This is also enforced by the compiler. This also gives well structured directory tree for our packages. See updated comment.

**Comment by xh3b4sd** [comment]
Why is `locker` not in `controller/internal`? I think it is not used anywhere but within the resources.

**Comment by kopiczko** [comment]
> Why is `locker` not in `controller/internal`? I think it is not used anywhere but within the resources.

I also thought abut this but it's injected into multiple controllers so it's created in `service/service.go`. I think it makes sense to set it up in a single place.

**Pull request merged**
