### PR TITLE
add separate hosted zone service

### PR DESCRIPTION
**Pull request by xh3b4sd**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

## Context

Towards https://github.com/giantswarm/giantswarm/issues/10832.

### CODE REVIEW

**Review by njuettner — APPROVED** [review]
LGTM, maybe also mention it in the CHANGELOG.md 🙂

**Comment by xh3b4sd** [comment]
What would you like to see in the changelog? I am not sure what to write there. It is also that there are no external implications since this is only an internal refactoring.

**Comment by njuettner** [comment]
Yeah good thought. I don't remember how we handled cluster-operator when starting with dropping the controller context.

**Comment by xh3b4sd** [comment]
Let's go with this. Successfully tested with `awscnfm plan 001` on `gauss`. 🚀

**Pull request merged**
