### PR TITLE
update flatcar amis to the latest stable releases

### PR DESCRIPTION
**Pull request by njuettner**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by njuettner** [comment]
Also ensured the AMI's in China are present.

**Review by calvix — APPROVED** [review]
lgtm but I would be hesitant with using latest flatcar in the 15.0.0 release as we encountered a bug  with clusters that have many services

**Comment by njuettner** [comment]
Sure, we can still merge it right? Even using a new operator release wouldn't do anything as long we don't change the flatcar version inside the release, right?

**Comment by calvix** [comment]
yes

**Pull request merged**
