### PR TITLE
Vendor

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Don't want to be impatient, but my builds are both hanging at this stage now for a couple of minutes already. Never saw that before. What is going on here? 

```
2018/02/22 16:39:16 {"caller":"github.com/giantswarm/aws-operator/service/alerter/service.go:294","info":"alerter service found 0 clusters with missing AWS resources","time":"2018-02-22 16:39:16.471"}
```

**Comment by xh3b4sd** [comment]
Saw this now. 

```
2018/02/22 16:39:16 {"caller":"github.com/giantswarm/aws-operator/service/alerter/service.go:294","info":"alerter service found 0 clusters with missing AWS resources","time":"2018-02-22 16:39:16.471"}
2018/02/22 16:44:16 unexpected error: waiting for guest cluster installed: waitTimeout
2018/02/22 16:44:16 Running command kubectl delete awsconfig ${CLUSTER_NAME}
```

**Comment by fgimenez** [comment]
Yes https://circleci.com/gh/giantswarm/aws-operator/3674 we hit this problem eventually, since we started using localkube (minikube running in circleCI machines with --vm-driver=none) sometimes the awsconfig object is created, apparently without problems, but the operator doesn't notice it, the creation is not triggered. After the timeout the awsconfig object is removed correctly (which indicates that it was actually there).

I haven't been able to reproduce locally, not sure what might be going on.

**Comment by xh3b4sd** [comment]
Something else we can do to improve the situation? Maybe shorter wait timeouts or something?

**Comment by fgimenez** [comment]
The timeout is already close to the creation times, that could affect normal builds. Maybe we could add more logging to understand the problem, but that could spam normal builds (which are by far much more frequent). Not sure, WDYT?

**Comment by xh3b4sd** [comment]
Adding logging is a good thing. Logs are spammy by nature. Knowing what is going on is a good thing.

**Comment by xh3b4sd** [comment]
I really don't like this but I am going to merge now without the full stack tests. They just don't work right now. This here is only a vendor update so it should be fine.

**Pull request merged**
