### PR TITLE
dep: update vendor

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by kopiczko** [comment]
Can I run e2e tests here? Did something change?

**Comment by xh3b4sd** [comment]
Circle seems to have issues.

**Comment by xh3b4sd** [comment]
Oh wow, now I reviewed twice. Good morning Tim. :D

**Comment by kopiczko** [comment]
Now I can be sure it's reviewed carefully.

**Comment by kopiczko** [comment]
e2e passed

**Pull request merged**
