### PR TITLE
Add in-cluster test

### PR DESCRIPTION
**Pull request by fgimenez**
First in-cluster e2e test, comes from #479 

The test just checks for the existence of the aws TPR in `e2e/tests/awstpr.go`. The file `e2e/tests/runner.go` probably belongs to e2e-harness project, will keep it here as we grow the e2e test suite to make development easier.

The sonobuoy results are saved as circleCI artifacts https://circleci.com/gh/giantswarm/aws-operator/1295#artifacts/containers/0, the string returned by the test is used as the testcase name.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Does this work only on circle or can I also run this on my local minikube?

**Comment by fgimenez** [comment]
@xh3b4sd absolutely, IMO it wouldn't make too much sense if the tests run on CI couldn't be executed locally, even before writing the production code that makes them pass. However, the changes are still in progress, almost done but not there yet, will ping you when ready (very soon hopefully).

This PR shows how the CI half looks like and, more importantly IMO, the test format, if we agree on that executing those same tests locally will be possible shortly.

**Comment by xh3b4sd** [comment]
Ack. Would be good to have some example that shows how to execute that locally at the end. As you already mentioned there are probably common parts we can extract to use them in different places without any hustle. The format for the config files is not so interesting to me personally. When we have some format we can use it and iterate on it IMO. Over time we will improve the format as needed. What I want to hold up though is to use the native way of executing golang tests. I would like to write a usual test method that is just being executed without the need to register it manually somewhere. So having a `Test_Foo` function in some `foo_test.go` file enables me to just execute `go test`. I would like to keep it that way. This integrates then nicely with the local development environment and any CI.

**Comment by fgimenez** [comment]
> The format for the config files is not so interesting to me personally. When we have some format we can use it and iterate on it IMO

Indeed, even now it can be (almost) totally removed, all the setup and teardown can be done in code in tests themselves.

> I would like to write a usual test method that is just being executed without the need to register it manually somewhere. So having a Test_Foo function in some foo_test.go file enables me to just execute go test. I would like to keep it that way. This integrates then nicely with the local development environment and any CI

That would be a problem in my opinion, we need a way to keep separated unit tests (quick feedback, rapid iterations) and e2e tests (full stack, slow feedback, execute-once-in-a-while kind of tests). If we have the e2e tests defined as the rest of the unit tests we lose this separation.

Also, in this case given that the tests are going to be executed as sonobuoy plugins (locally too), we can't run them with just `go test`, the `e2e-harness` cli tool will be needed (just two calls, as in CI, `e2e-harness setup` and `e2e-harness test`). That way we make sure that we have exactly the same test environments wherever those e2e tests are executed. Let me know what do you think.

If we continue with this approach I think we can do better in terms of test registration, using reflection could make this completely transparent I think, but it would be just a matter of iterating.

**Comment by xh3b4sd** [comment]
> That would be a problem in my opinion, we need a way to keep separated unit tests (quick feedback, rapid iterations) and e2e tests (full stack, slow feedback, execute-once-in-a-while kind of tests). If we have the e2e tests defined as the rest of the unit tests we lose this separation.

For separation purposes there are build tags. You can add arbitrary build tags to your tests and execute them as you like. 

> Let me know what do you think.

I think you know what you are doing. I just wanted to give feedback from my current naive point of view. I think this is going into a good direction. All good.

**Comment by fgimenez** [comment]
> For separation purposes there are build tags. You can add arbitrary build tags to your tests and execute them as you like.

Yep you are right, we could also use dot directories for not executing part of the tests. There's another issue with this approach tough, a single `go test` call would need to run the whole thing, create the test cluster (on CI only), set it up, create the test binary, create the test image, deploy the sonobuoy infrastructure, deploy the sonobuoy plugin and retrieve the tests results, all this in a single step. This can be (arguably) good for a local execution but definitely bad for CI, where we aim to have separate build steps that can be repeated, executed concurrently and terminated with a common step, all of this in isolation from each other. In order to replicate that same behavior locally IMO a cli tool is more helpful.

> I think you know what you are doing. I just wanted to give feedback from my current naive point of view. I think this is going into a good direction. All good.

Thanks a lot Tim, that's super encouraging, and your feedback is more than helpful <3

**Pull request merged**
