### PR TITLE
Readme: update docker image URL

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by asymmetric** [comment]
BTW the GitHub diff highlighter fails so hard here.

**Comment by kopiczko** [comment]
@asymmetric not that much as when you have indentation changed, I wish it had `-w` option :)

**Comment by asymmetric** [comment]
It does! Append `?w=1` to the URL. https://github.com/blog/967-github-secrets

**Comment by asymmetric** [comment]
But the problem here is that it's highlighting somthing that **didn't** change!

**Comment by kopiczko** [comment]
OMG thank you ❤️ `?w=1`

**Pull request merged**
