### PR TITLE
Cloud config unit test

### PR DESCRIPTION
**Pull request by mazzy89**
Add cluster certs as fixtures in unit test to have more robust render template

### CODE REVIEW

**Comment by mazzy89** [comment]
* Unfortunately reverting the fix does not make fail the tests which mean that yes it is not sufficient. I'm wondering if there is any exact cert that makes fail the test and naturally if so we can't use that cert as fixtures 😩
* Yes, I agree to create a different test case

**Comment by mazzy89** [comment]
We actually mock the encrypter so we deviate a bit from the real use case so the problem could be that. Any idea on this?

**Comment by xh3b4sd** [comment]
Are the certificates you added as fixtures actually the certs breaking a real cluster? The encrypter we use in production is either KMS or Vault. IIRC the KMS encrypter causes the issues we see so far. Not sure if using KMS in a unit test makes sense.

**Comment by mazzy89** [comment]
> Are the certificates you added as fixtures actually the certs breaking a real cluster?

No, for two reasons:

* I don't know exactly which are the certs that brake the cluster
* I can't use "real" certificates as fixtures. One of them is a private key so I can't push to GH. 

Yes, in my opinion using KMS in an unit test and hence make API calls to an external service is not under the scope of unit test. Perhaps we are at the point to consider this as an improvement for e2e tests?

**Pull request closed without merging**
