### PR TITLE
Switch v22 to ignition v4.1.0

### PR DESCRIPTION
**Pull request by corest**
Current WIP version of the ignition is `4.1.0`

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Note that the scaling and draining test are likely to fail. I am working on that already.

**Comment by xh3b4sd** [comment]
Let us know when we can help you with that later. Decision from product was now to not release ignition with AS.

**Comment by corest** [comment]
I'm not sure what are you talking about. ignition is already in active release. This PR is just about moving to the new ignition version

**Comment by xh3b4sd** [comment]
I see. Reading helps. When this is only the update of the ignition version, we should just merge it now.

**Comment by corest** [comment]
Ignition was there. And this change is not critical in that sense. It is just about bringing new changes we added into ignition. We should not merge it now and I'm fine to move it into v23

**Comment by corest** [comment]
This is done already in v23

**Pull request closed without merging**
