### PR TITLE
[WIP] add missing DNS Record type when deleting

### PR DESCRIPTION
**Pull request by asymmetric**
# WIP

Omitting it resulted in an API error.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
What about this PR? Is it still relevant? Should we close it?

**Comment by asymmetric** [comment]
If you don't see this error then yes, this can be closed.

**Comment by xh3b4sd** [comment]
I am not into details. Just want to trigger boyscouting. :D /cc @rossf7 @kopiczko

**Comment by rossf7** [comment]
I'll pick up this boyscouting :)

**Comment by rossf7** [comment]
Closing in favour of #361 

@asymmetric thanks for the fix <3

**Pull request closed without merging**
