### PR TITLE
detach role policies upon node pool deletion

### PR DESCRIPTION
**Pull request by xh3b4sd**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

## Context 

Fixes https://github.com/giantswarm/giantswarm/issues/14691. I tested the cleanup manually in a little go script. There should never be more than a handful attached policies on a given role.

### CODE REVIEW

**Review by njuettner — APPROVED** [review]

**Comment by calvix** [comment]
how about polices attached to tccpn role? I think we should clean them too

**Comment by calvix** [comment]
Also, I miss code where you  add this resource to any operator kit controller so this code is now unused

**Comment by xh3b4sd** [comment]
I split my PRs. I added and wired the resource in https://github.com/giantswarm/aws-operator/pull/2932. The PM was only about the node role of the node pools. I can add the same logic for the control plane.

**Comment by calvix** [comment]
> I split my PRs. I added and wired the resource in #2932. The PM was only about the node role of the node pools. I can add the same logic for the control plane.

OK I missed that previous PR, so the code is good for NP but yeah I would also like to see it for the control plane as well as I think it makes a lot of sense

**Review by calvix — APPROVED** [review]
LGTM for NP, lets tackle the COntrol plane in another PR

**Pull request merged**
