### PR TITLE
Add method 'get' for service resource in RBAC

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/2551

### CODE REVIEW

**Comment by kopiczko** [comment]
@marians I believe `get` is the only one missing in the list.

**Comment by pipo02mix** [comment]
If you follow the commits history, you will see how I started with 'get' and then I discovered now aws-operator needs all verbs :)

**Comment by marians** [comment]
Yeah, I saw that. But that history is lost after a merge commit. And as we sometimes go back through the commit history to explain a change, a PR title that explains the actual change is helpful.

**Comment by marians** [comment]
To illustrate what I mean, this is the history as it's looking now:

image

**Pull request merged**
