### PR TITLE
WIP: Split AWS/IAM policies for master and workers

### LINKED ISSUE #330: Split AWS/IAM policies for master and workers
As the master needs much more permissions (especially if we at some point enable more cloud functionality) it would be good to keep policies separate, similar to following:
https://github.com/kubernetes/kubernetes/tree/release-1.5/cluster/aws/templates/iam

### PR DESCRIPTION
**Pull request by rossf7**
Fixes #330

### CODE REVIEW

**Comment by rossf7** [comment]
Creating separate policies works but the worker policy now has restricted EC2 permissions. This is as per the cloud provider docs but I need to test the persistent volumes still work.

**Comment by hobti01** [comment]
@rossf7 could you please add the following to the policy on the master and workers to allow image pulling from ECR as implemented in https://github.com/kubernetes/kubernetes/pull/19447 and https://github.com/kubernetes/kubernetes/pull/24369

See also PR https://github.com/giantswarm/aws-operator/pull/364

```
{
"Effect": "Allow",
    "Action": [
        "ecr:GetAuthorizationToken",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        "ecr:GetRepositoryPolicy",
        "ecr:DescribeRepositories",
        "ecr:ListImages",
        "ecr:BatchGetImage"
    ],
    "Resource": "*"
}
```

**Comment by rossf7** [comment]
Hi @hobti01 I think it's best that this is handled as a separate change. Thanks for providing your PR we'll get that reviewed.

**Comment by rossf7** [comment]
Closing as this was implemented in #370. ECR permissions are now only applied to worker nodes.

**Pull request closed without merging**
