### PR TITLE
create internal etcd ELB 

### PR DESCRIPTION
**Pull request by fgimenez**
Still not tested, will comment here when done. Also using custom logic for checking for new deployment (just in place to test the rest).

### CODE REVIEW

**Comment by calvix** [comment]
I see a problem where we by default connect to etcd on port 443 (both on-prem and aws - both k8s-apiserver and calico)
and if we remove the ELB we need to connect to 2379

Also, this may require some changes in a security group.

**Comment by fgimenez** [comment]
> Also, this may require some changes in a security group.

@calvix AIUI all the traffic between workers and masters is allowed https://github.com/giantswarm/aws-operator/blob/master/service/create/security_group.go#L104 is that correct?

**Comment by calvix** [comment]
Yep, that will for sure break KVM.
Easy solution would be let etcd listen also on 443 but that is already taken by k8s-api so we cant do that.

**Comment by rossf7** [comment]
Ack. OK listening on 443 isn't going to work. I can see 2 options
 
- Move etcd to a different port which will also affect KVM.
- Use a private ELB and have it listen on 443

WDYT?

**Comment by fgimenez** [comment]
+1 for the private ELB

**Comment by calvix** [comment]
changing etcd port is problematic as this need to be configured on  LB that are often in customers hands.
I would go for private ELB now.

In long term we will be accessing etcd via localhost for k8s-api and calico will use k8s datastore so the ELB will be removed.

**Comment by rossf7** [comment]
Cool yes agree private ELB is the best option. Thanks for flagging this @calvix

**Comment by fgimenez** [comment]
Thank you guys, on it

**Comment by fgimenez** [comment]
With this the creation seems to work but the nodes don't come up, probably etcd not accessible, any idea?
```
$ kubectl get nodes
NAME                                           STATUS     AGE       VERSION
ip-10-1-12-196.eu-central-1.compute.internal   NotReady   7m        v1.7.3+coreos.0
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl describe node ip-10-1-12-196.eu-central-1.compute.internal 
Name:			ip-10-1-12-196.eu-central-1.compute.internal
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=m3.medium
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=eu-central-1
			failure-domain.beta.kubernetes.io/zone=eu-central-1a
			ip=10.1.12.196
			kubernetes.io/hostname=
			node-role.kubernetes.io/master=
			role=master
Annotations:		node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			node-role.kubernetes.io/master:NoSchedule
CreationTimestamp:	Wed, 11 Oct 2017 15:47:46 +0200
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Wed, 11 Oct 2017 15:55:35 +0200 	Wed, 11 Oct 2017 15:47:46 +0200 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Wed, 11 Oct 2017 15:55:35 +0200 	Wed, 11 Oct 2017 15:47:46 +0200 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Wed, 11 Oct 2017 15:55:35 +0200 	Wed, 11 Oct 2017 15:47:46 +0200 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		False 	Wed, 11 Oct 2017 15:55:35 +0200 	Wed, 11 Oct 2017 15:47:46 +0200 	KubeletNotReady 		runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Addresses:
  InternalIP:	10.1.12.196
  Hostname:	ip-10-1-12-196.eu-central-1.compute.internal
Capacity:
 cpu:		1
 memory:	3857388Ki
 pods:		110
Allocatable:
 cpu:		1
 memory:	3754988Ki
 pods:		110
System Info:
 Machine ID:			
 System UUID:			EC21B2D4-EBCA-3442-F014-D4E604CA3E62
 Boot ID:			beec946f-4f37-4e67-9e3f-fdbf8bf9f5fd
 Kernel Version:		4.9.24-coreos
 OS Image:			Container Linux by CoreOS 1353.7.0 (Ladybug)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.7.3+coreos.0
 Kube-Proxy Version:		v1.7.3+coreos.0
ExternalID:			i-0f51328e6688c1545
Non-terminated Pods:		(0 in total)
  Namespace			Name		CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----		------------	----------	---------------	-------------
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  0 (0%)	0 (0%)		0 (0%)		0 (0%)
Events:
  FirstSeen	LastSeen	Count	From								SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----								-------------	--------	------			-------
  9m		9m		1	kube-proxy, ip-10-1-12-196.eu-central-1.compute.internal			Normal		Starting		Starting kube-proxy.
  9m		9m		1	kubelet, ip-10-1-12-196.eu-central-1.compute.internal				Normal		Starting		Starting kubelet.
  9m		9m		1	kubelet, ip-10-1-12-196.eu-central-1.compute.internal				Normal		NodeAllocatableEnforced	Updated Node Allocatable limit across pods
  9m		7m		18	kubelet, ip-10-1-12-196.eu-central-1.compute.internal				Normal		NodeHasSufficientDisk	Node ip-10-1-12-196.eu-central-1.compute.internal status is now: NodeHasSufficientDisk
  9m		7m		18	kubelet, ip-10-1-12-196.eu-central-1.compute.internal				Normal		NodeHasSufficientMemory	Node ip-10-1-12-196.eu-central-1.compute.internal status is now: NodeHasSufficientMemory
  9m		7m		18	kubelet, ip-10-1-12-196.eu-central-1.compute.internal				Normal		NodeHasNoDiskPressure	Node ip-10-1-12-196.eu-central-1.compute.internal status is now: NodeHasNoDiskPressure
```
From route53:
```
etcd.test-cluster.gauss.eu-central-1.aws.gigantic.io. | A | ALIAS internal-test-cluster-etcd-1128026488.eu-central-1.elb.amazonaws.com. (z215jyrzr1tbd5) | No
-- | -- | -- | --
```

**Comment by rossf7** [comment]
Are there any errors from Calico on the workers connecting to etcd? I think it has to be running before the nodes will report as healthy.

I checked the ELBs and etcd and api are running so the master seems OK.

**Comment by fgimenez** [comment]
@rossf7 this is the complete `journalctl -xe` output from one of the workers http://paste.ubuntu.com/25720758/

**Comment by calvix** [comment]
i can help if you have trouble debugging

**Comment by fgimenez** [comment]
@calvix thx! from the log above not sure what this means:
```
Unable to register node "ip-10-1-12-136.eu-central-1.compute.internal" with API server: User "worker.test-cluster.gauss.eu-central-1.aws.gigantic.io" cannot create nodes at the cluster scope. (post nodes)
```
btw i've just added your public key to one of the workers:
```
$ ssh ${USER}@52.57.142.175
```

**Comment by calvix** [comment]
Can you post ips of the cluster so i can try test tomorrow?

**Comment by calvix** [comment]
this looks like RBAC issue, @puja108 any idea?

**Comment by fgimenez** [comment]
Looks related to RBAC, on master:
```
$ cat /etc/systemd/system/k8s-api-server.service | grep RBAC
--authorization-mode=RBAC \
```

**Comment by fgimenez** [comment]
Looks related to RBAC, on master:
```
$ cat /etc/systemd/system/k8s-api-server.service | grep RBAC
--authorization-mode=RBAC \
```

**Comment by puja108** [comment]
Sound like RBAC, but `worker.` CN should have node role bound to it: https://github.com/giantswarm/k8scloudconfig/blob/master/v_0_1_0/master_template.go#L768-L780

Could it be that this breaks in local testing cause of the templating? Maybe check the roles and role bindings.

**Comment by fgimenez** [comment]
@calvix about the ips: workers 18.194.183.153 and 52.57.142.175, master 18.194.155.2, i've already added your public key to all of them.

@puja108 no `kubelet` clusterrolebinding:
```
$ kubectl get clusterrolebinding
NAME                                           AGE
calico-node                                    2h
calico-policy-controller                       2h
cluster-admin                                  2h
giantswarm-admin                               2h
kube-controller-manager                        2h
kube-dns                                       2h
kube-scheduler                                 2h
nginx-ingress-controller                       2h
system:basic-user                              2h
system:controller:attachdetach-controller      2h
system:controller:certificate-controller       2h
system:controller:cronjob-controller           2h
system:controller:daemon-set-controller        2h
system:controller:deployment-controller        2h
system:controller:disruption-controller        2h
system:controller:endpoint-controller          2h
system:controller:generic-garbage-collector    2h
system:controller:horizontal-pod-autoscaler    2h
system:controller:job-controller               2h
system:controller:namespace-controller         2h
system:controller:node-controller              2h
system:controller:persistent-volume-binder     2h
system:controller:pod-garbage-collector        2h
system:controller:replicaset-controller        2h
system:controller:replication-controller       2h
system:controller:resourcequota-controller     2h
system:controller:route-controller             2h
system:controller:service-account-controller   2h
system:controller:service-controller           2h
system:controller:statefulset-controller       2h
system:controller:ttl-controller               2h
system:discovery                               2h
system:kube-controller-manager                 2h
system:kube-dns                                2h
system:kube-scheduler                          2h
system:node                                    2h
system:node-proxier                            2h
```

**Comment by puja108** [comment]
That's strange, how did that get lost? I can only guess there's an error in the template that made that binding (yaml) fail. Seems like all bindings that contained `{{.Cluster.Kubernetes.Kubelet.Domain}}` are missing, all others are there.

**Comment by puja108** [comment]
yes, exactly

**Comment by fgimenez** [comment]
ok, i'll delete the cluster now that it's clear what happened, thx!

**Comment by fgimenez** [comment]
Working fine with current master after the encryption fix (thx @jgsqware! :))
```
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl get nodes
NAME                                           STATUS    AGE       VERSION
ip-10-1-12-147.eu-central-1.compute.internal   Ready     2m        v1.7.5+coreos.0
ip-10-1-12-189.eu-central-1.compute.internal   Ready     2m        v1.7.5+coreos.0
ip-10-1-12-224.eu-central-1.compute.internal   Ready     2m        v1.7.5+coreos.0
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl get pods --all-namespaces 
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-node-rp1wt                          2/2       Running   0          2m
kube-system   calico-node-t7zj0                          2/2       Running   0          2m
kube-system   calico-node-vp7w6                          2/2       Running   0          2m
kube-system   calico-policy-controller-59090804-v6k0t    1/1       Running   0          2m
kube-system   default-http-backend-2945164050-0gh53      1/1       Running   0          2m
kube-system   default-http-backend-2945164050-4wp0k      1/1       Running   0          2m
kube-system   kube-dns-4244741379-q7rbr                  3/3       Running   0          2m
kube-system   kube-dns-4244741379-rnpvc                  3/3       Running   0          2m
kube-system   kube-dns-4244741379-z8s9m                  3/3       Running   0          2m
kube-system   nginx-ingress-controller-327853665-5k8dl   1/1       Running   0          2m
kube-system   nginx-ingress-controller-327853665-5nzpw   1/1       Running   0          2m
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl run --rm -i -t busybox --image=busybox -- sh
If you don't see a command prompt, try pressing enter.
/ # nslookup google.com
Server:    172.31.0.10
Address 1: 172.31.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2a00:1450:4001:819::200e fra16s13-in-x0e.1e100.net
Address 2: 172.217.18.14 fra02s19-in-f14.1e100.net
/ # exit
Session ended, resume using 'kubectl attach busybox-4158955249-zz0lq -c busybox -i -t' command when the pod is running
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ export DNS="nginx1.test-cluster.k8s.gauss.eu-central-1.aws.gigantic.io"
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ wget https://gist.githubusercontent.com/r7vme/bf7b9d8baf5e709f137a23ec6c105b05/raw/4f6811ffeb0c12e48663fb31de29790ced021295/gistfile1.txt -O ingress_test.yaml
--2017-10-13 18:29:30--  https://gist.githubusercontent.com/r7vme/bf7b9d8baf5e709f137a23ec6c105b05/raw/4f6811ffeb0c12e48663fb31de29790ced021295/gistfile1.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 151.101.132.133
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|151.101.132.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 847 [text/plain]
Saving to: ‘ingress_test.yaml’

ingress_test.yaml                                                   100%[==================================================================================================================================================================>]     847  --.-KB/s    in 0s      

2017-10-13 18:29:30 (161 MB/s) - ‘ingress_test.yaml’ saved [847/847]

fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ sed -i "s/PUT_SITE_DNS_HERE/${DNS}/" ingress_test.yaml
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl apply -f ingress_test.yaml
deployment "nginx-for-ingress-deployment" created
service "nginx-for-ingress-service" created
ingress "nginx-for-ingress-ingress" created
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ curl ${DNS}
default backend - 404fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ 
fgimenez@dunwich:~/workspace/gocode/src/github.com/giantswarm/aws-operator$ kubectl delete -f ingress_test.yaml 
deployment "nginx-for-ingress-deployment" deleted
service "nginx-for-ingress-service" deleted
ingress "nginx-for-ingress-ingress" deleted
```

**Comment by fgimenez** [comment]
Thx! :)

**Comment by rossf7** [comment]
Towards giantswarm/giantswarm#1803 (just for tracking).

**Pull request merged**
