### PR TITLE
Update microkit and enable debug server

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/4088.

### CODE REVIEW

**Comment by oponder** [comment]
The dependency issue should be resolved now: https://github.com/giantswarm/e2etests/pull/17

If you `dep ensure --update` again and change:

`b := backoff.NewExponential(framework.ShortMaxWait, framework.ShortMaxInterval)`
to
`b := backoff.NewExponential(backoff.ShortMaxWait, backoff.ShortMaxInterval)`

in `integration/setup/setup.go`

Let me know if you want me to apply that here for you, or if you can take it from here.

**Comment by indyfree** [comment]
Already merged the aforementioned changes in #1198 . So you should be good to go from here on.

**Comment by xh3b4sd** [comment]
This still fails with the following error consistently. 

```
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/e2e-harness/pkg/framework/host.go:464","level":"debug","message":"k8s secret is there","time":"2018-10-08T10:28:30.287582+00:00"}
2018/10/08 10:28:30 [{/home/circleci/.go_workspace/src/github.com/giantswarm/aws-operator/integration/setup/setup.go:296: } {/home/circleci/.go_workspace/src/github.com/giantswarm/aws-operator/integration/setup/setup.go:165: } {/home/circleci/.go_workspace/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/apiextensions_aws_config_e2e.go:57: chartvalues.APIExtensionsAWSConfigE2EConfig.AWS.VPCPeerID must not be empty} {invalid config error}]
```

Who knows something about this?

**Comment by kopiczko** [comment]
I implemented this error. We can talk after our planning.

**Comment by kopiczko** [comment]
@xh3b4sd I see you updated to the lasted master 12 days ago. Fix should be in newest master.

**Comment by xh3b4sd** [comment]
My hunch is the VPC IDs are missing because we maybe cannot allocate any due to https://github.com/giantswarm/giantswarm/issues/4347.

**Comment by kopiczko** [comment]
> I merged master today.

I can confirm my fix is in place. We probably should check for CF status for `CREATE_COMPLETE` before taking the output.

**Comment by kopiczko** [comment]
https://github.com/giantswarm/giantswarm/issues/4354

**Comment by xh3b4sd** [comment]
Same as with https://github.com/giantswarm/aws-operator/pull/1204#issuecomment-427857760. Going.

**Pull request merged**
