### PR TITLE
Encrypt ebs volume at rest

### PR DESCRIPTION
**Pull request by jgsqware**
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

fixes https://github.com/giantswarm/vodafone/issues/243

### CODE REVIEW

**Comment by jgsqware** [comment]
@puja108 Need some insight about KMS here

**Comment by puja108** [comment]
Doesn't AWS just use some key by default if we don't give it any special key? Like with the other EBS in storage class, I don't think we need to control keys for these.

**Comment by jgsqware** [comment]
For Worker, it's working, EBS is encrypted because it's linked to the launch configuration, not to a snapshot

For Master, the instance is linked to a snapshot that is not currently encrypted. I'll continue digging on this

**Comment by puja108** [comment]
For master we can leave this out I think, as master is reserved for us and not used for user data which is the use case for their encryption. @othylmann WDYT?

**Comment by jgsqware** [comment]
Ok if good for @othylmann I'll merge it

**Comment by othylmann** [comment]
Yep, should be fine @puja108 @jgsqware

**Pull request merged**
