### PR TITLE
update-flatcar-version

### PR DESCRIPTION
**Pull request by calvix**
the `2605.12.0` flatcar has few more fixes for CVEs so let's include it in 14.0.0 release

### CODE REVIEW

**Comment by MarcelMue** [comment]
Please wait on this one a little bit - currently the push to china is messed up. So there is no image in cn-north-1

**Comment by calvix** [comment]
oh that is sad

**Comment by paurosello** [comment]
I will need to update the AMI list for release 9.3.8 too

**Comment by calvix** [comment]
works now

**Review by MarcelMue — APPROVED** [review]

**Pull request merged**
