### PR TITLE
project: bump version to 7.0.0-dev

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by sslavic** [comment]
I'm testing removal of ingress controller related resources from aws-operator and it's failing to start with

```
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/client/k8srestconfig/k8s_rest_config.go:148","level":"debug","message":"creating in-cluster REST config","time":"2019-11-01T20:15:56.090788+00:00"}
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/client/k8srestconfig/k8s_rest_config.go:155","level":"debug","message":"created in-cluster REST config","time":"2019-11-01T20:15:56.090994+00:00"}
panic: [{/go/src/github.com/giantswarm/aws-operator/service/service.go:325: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/microendpoint/service/version/service.go:54: } {/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/versionbundle/bundles.go:38: patch version must be positive number: invalid bundle} {invalid bundles}]

goroutine 1 [running]:
main.mainE.func1(0xc00017e200, 0xc00017e900, 0xc0000b8f00)
	/go/src/github.com/giantswarm/aws-operator/main.go:58 +0x1fb
github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/microkit/command/daemon.(*command).Execute(0xc0005afef0, 0xc000025400, 0xc000822a80, 0x0, 0x4)
	/go/src/github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/microkit/command/daemon/command.go:104 +0x1ac
github.com/giantswarm/aws-operator/vendor/github.com/spf13/cobra.(*Command).execute(0xc000025400, 0xc000822a00, 0x4, 0x4, 0xc000025400, 0xc000822a00)
	/go/src/github.com/giantswarm/aws-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/giantswarm/aws-operator/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000025b80, 0xc000025b80, 0xc0000a5bc0, 0x22)
	/go/src/github.com/giantswarm/aws-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/giantswarm/aws-operator/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/giantswarm/aws-operator/vendor/github.com/spf13/cobra/command.go:864
main.mainE(0x258bfa0, 0xc0000ae000, 0x0, 0xc00009a058)
	/go/src/github.com/giantswarm/aws-operator/main.go:165 +0x23ce
main.main()
	/go/src/github.com/giantswarm/aws-operator/main.go:24 +0x3d
```

Is the `-dev` suffix cause of this?

**Comment by kopiczko** [comment]
@sslavic likely. We'll discuss this in my team. I'll try to push a solution ASAP.

**Comment by kopiczko** [comment]
If it blocks bump it to `7.0.1`.

**Comment by kopiczko** [comment]
The issue reported by @sslavic is sorted on master.

**Pull request merged**
