### PR TITLE
remove collector from aws-operator

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards: https://github.com/giantswarm/giantswarm/issues/12651
We are moving the collector to https://github.com/giantswarm/aws-collector

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I think we should only merge this when we have the separate collector running. Not sure how far we are with this already. I was thinking in case we need to release the operator on Monday we would roll something out that does not cover all of our metrics we might need.

**Comment by anvddriesch** [comment]
We can look at what's still needed to release the `aws-collector` together.
However, as long as other versions of the `aws-operator` are deployed, the metrics will be there regardless.

**Comment by anvddriesch** [comment]
We released `aws-collector`. From my side we can merge this.

**Comment by xh3b4sd** [comment]
Not blocking this. Somebody can approve when this is fine. 🙈

**Review by njuettner — APPROVED** [review]
Agreed with Antonia to wait until Monday. 
I can see more and more aws-collector getting rolled out, we wanted to ensure everything is ok and give it a bit time over the weekend.

**Comment by xh3b4sd** [comment]
You two got this. 🚀

**Pull request merged**
