### PR TITLE
legacy: Legacy release revision

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#10098

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by tfussell** [comment]
I have this change in the `legacy-update-helm` branch already: https://github.com/giantswarm/aws-operator/blob/25a197520cd84eddc785af438a87c1fe8c0492e2/helm/aws-operator/templates/deployment.yaml#L19 This should be merged into `legacy` tomorrow. I don't mind at all if you merge this to `legacy` then I can rebase my branch--just wanted to mention.

**Comment by tfussell** [comment]
P.S. I appreciate the explicit backport into `legacy`. Sometimes it's hard to know which `master` changes should be brought into `legacy`.

**Comment by rossf7** [comment]
Tested on `ginger`.

**Comment by rossf7** [comment]
@tfussell Ah it was this PR :)

The problem is even once the app CR is deployed we need to update the helm release if the values will change. Helm 3 can't template `Release.Time` so the release will fail.

So I'll also need to "reissue" the tarballs for the active releases.

**Comment by rossf7** [comment]
>  Let's use @giantswarm/team-firecracker-pe next time then we do not bother Marian with this.

@xh3b4sd Ack. 👍

**Pull request merged**
